import App from "@/components/App";
import "./globals.css";
import { Inter } from "next/font/google";
import StoreProvidor from "@/redux/StoreProvidor";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvidor>
          <App>{children}</App>
        </StoreProvidor>
      </body>
    </html>
  );
}
