export const data = {
  products: [
    {
      id: 1,
      name: "product1",
      price: 500,
      stocks: 5,
      rattings: 4,
      numOfReview: 10,
      info: "quality is good",
      image: "/images/photo1.jpg",
    },
    {
      id: 2,
      name: "product2",
      price: 500,
      stocks: 55,
      rattings: 4,
      numOfReview: 10,
      info: "quality is good",
      image: "/images/photo2.jpg",
    },
    {
      id: 3,
      name: "product3",
      price: 500,
      stocks: 5,
      rattings: 4,
      numOfReview: 10,
      info: "quality is good",
      image: "/images/photo3.jpg",
    },
    {
      id: 4,
      name: "product4",
      price: 500,
      stocks: 6,
      rattings: 4,
      numOfReview: 10,
      info: "quality is good",
      image: "/images/photo4.jpg",
    },
    {
      id: 5,
      name: "product5",
      price: 500,
      stocks: 4,
      rattings: 4,
      numOfReview: 10,
      info: "quality is good",
      image: "/images/photo5.jpg",
    },
  ],
};
